version: "3.9"
services:
  threadslapper:
    image: threadslapper:latest
    build:
      context: .
    environment:
      # Discord bot token
      THREADSLAPPER_TOKEN: ${THREADSLAPPER_TOKEN:?THREADSLAPPER_TOKEN not set.}
      # Frequency in which the bot should check the RSS feed.
      THREADSLAPPER_CHECK_INTERVAL_MIN: ${THREADSLAPPER_CHECK_INTERVAL_MIN:-5}
      # Should the bot perform a latest episode check on startup?
      THREADSLAPPER_STARTUP_LATEST_EPISODE_CHECK: ${THREADSLAPPER_STARTUP_LATEST_EPISODE_CHECK:-true}

      # The yaml file that specifies multiple RSS feeds
      THREADSLAPPER_CONFIG_FILE: ${THREADSLAPPER_CONFIG_FILE:-example_config.yml}
      # Alternatively, a single RSS feed + channel ID
      # THREADSLAPPER_CHANNEL__TITLE: ${THREADSLAPPER_CHANNEL__TITLE:?THREADSLAPPER_CHANNEL__TITLE not set}
      # THREADSLAPPER_CHANNEL__CHANNEL_ID: ${THREADSLAPPER_CHANNEL__CHANNEL_ID:?THREADSLAPPER_CHANNEL__CHANNEL_ID not set.}
      # THREADSLAPPER_CHANNEL__RSS_FEED: ${THREADSLAPPER_CHANNEL__RSS_FEED:?THREADSLAPPER_CHANNEL__RSS_FEED not set.}

      # Override channel and announcement channel IDs in bulk with these, can be blank or commented out.
      # THREADSLAPPER_OVERRIDE_CHANNEL_ID: ${THREADSLAPPER_OVERRIDE_CHANNEL_ID}
      # THREADSLAPPER_ANNOUNCE_OVERRIDE_CHANNEL_ID: ${THREADSLAPPER_OVERRIDE_ANNOUNCE_CHANNEL_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $PWD/config:/opt/threadslapper/config
      - $PWD/threadslapper_log:/var/log/threadslapper
    labels:
      - "traefik.enable=false"
    restart: always
